/* =============================================================================
   01_demo_objects.sql — database, warehouses, schemas
   -----------------------------------------------------------------------------
   SYSADMIN creates, then hands ownership to OF_KAFKA_ADMIN.
   ============================================================================= */

USE ROLE SYSADMIN;

/* --- Warehouse (SMALL) --- */
CREATE WAREHOUSE IF NOT EXISTS OF_KAFKA_WH
    WAREHOUSE_SIZE      = 'SMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Kafka demo — queries, connector, and dynamic tables';

/* --- Database (Iceberg-enabled) --- */
CREATE DATABASE IF NOT EXISTS OF_KAFKA
    COMMENT = 'Kafka Openflow cold chain monitoring demo';

/* --- Hand ownership --- */
GRANT OWNERSHIP ON DATABASE  OF_KAFKA    TO ROLE OF_KAFKA_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE OF_KAFKA_WH TO ROLE OF_KAFKA_ADMIN COPY CURRENT GRANTS;

/* --- Iceberg settings (as owner) --- */
USE ROLE OF_KAFKA_ADMIN;

ALTER DATABASE OF_KAFKA SET
    EXTERNAL_VOLUME              = 'SNOWFLAKE_MANAGED'
    STORAGE_SERIALIZATION_POLICY = COMPATIBLE
    ICEBERG_VERSION_DEFAULT      = 3;

USE DATABASE OF_KAFKA;

/* --- Schemas --- */
CREATE SCHEMA IF NOT EXISTS INGEST
    COMMENT = 'Kafka sensor data, dynamic tables, alarm events';

CREATE SCHEMA IF NOT EXISTS OPENFLOW
    COMMENT = 'Gen 2 Openflow deployment + runtime objects';

DROP SCHEMA IF EXISTS PUBLIC;

/* --- Event table for runtime telemetry --- */
USE ROLE ACCOUNTADMIN;

CREATE EVENT TABLE IF NOT EXISTS OF_KAFKA.INGEST.DEMO_EVENTS
    COMMENT = 'Openflow runtime + task telemetry';

ALTER ACCOUNT SET EVENT_TABLE = OF_KAFKA.INGEST.DEMO_EVENTS;
ALTER ACCOUNT SET LOG_LEVEL   = INFO;
ALTER ACCOUNT SET TRACE_LEVEL = ON_EVENT;

USE ROLE OF_KAFKA_ADMIN;

/* --- Grant runtime role access --- */
GRANT USAGE ON DATABASE OF_KAFKA TO ROLE OF_KAFKA_RUNTIME_ROLE;

GRANT USAGE ON SCHEMA OF_KAFKA.INGEST TO ROLE OF_KAFKA_RUNTIME_ROLE;
GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE STAGE, CREATE SEQUENCE,
      CREATE CORTEX SEARCH SERVICE
    ON SCHEMA OF_KAFKA.INGEST TO ROLE OF_KAFKA_RUNTIME_ROLE;

GRANT USAGE, OPERATE ON WAREHOUSE OF_KAFKA_WH
    TO ROLE OF_KAFKA_RUNTIME_ROLE;

GRANT USAGE ON SCHEMA OF_KAFKA.OPENFLOW TO ROLE OF_KAFKA_RUNTIME_ROLE;

/* --- FUTURE TABLES so we can SELECT on connector-created objects --- */
USE ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OF_KAFKA.INGEST
    TO ROLE OF_KAFKA_ADMIN;
USE ROLE OF_KAFKA_ADMIN;

/* --- Verify --- */
SHOW PARAMETERS LIKE 'EXTERNAL_VOLUME'              IN DATABASE OF_KAFKA;
SHOW PARAMETERS LIKE 'STORAGE_SERIALIZATION_POLICY' IN DATABASE OF_KAFKA;
SHOW PARAMETERS LIKE 'ICEBERG_VERSION_DEFAULT'      IN DATABASE OF_KAFKA;
SHOW SCHEMAS IN DATABASE OF_KAFKA;
SHOW WAREHOUSES LIKE 'OF_KAFKA%';
